import re
from typing import Any, Dict, Iterable, List, Optional

from fpdf import FPDF


def _safe_filename(value: str) -> str:
    v = (value or "").strip()
    v = re.sub(r"\s+", "_", v)
    v = re.sub(r"[^a-zA-Z0-9_\-]", "", v)
    return (v or "report")[:60]


def clean_text(text: Any) -> str:
    s = "" if text is None else str(text)
    s = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F]", " ", s)
    s = " ".join(s.split())
    try:
        return s.encode("latin-1", "replace").decode("latin-1")
    except Exception:
        return "".join(ch if ord(ch) < 256 else "?" for ch in s)


def generate_audit_pdf(
    *,
    business_name: str,
    phone: Optional[str],
    issues: Iterable[Dict[str, Any]],
) -> bytes:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", style="B", size=16)
    pdf.cell(0, 10, clean_text("AUDIT DIAGNOSTICO DIGITALE"), ln=True)

    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(60)
    pdf.cell(0, 7, clean_text(f"Cliente: {business_name}"), ln=True)
    if phone:
        pdf.cell(0, 7, clean_text(f"Telefono: {phone}"), ln=True)
    pdf.ln(3)

    pdf.set_text_color(20)
    pdf.set_font("Helvetica", style="B", size=12)
    pdf.cell(0, 8, clean_text("Problemi tecnici rilevati"), ln=True)

    issues_list: List[Dict[str, Any]] = list(issues or [])
    if not issues_list:
        pdf.set_font("Helvetica", size=11)
        pdf.multi_cell(0, 6, clean_text("Nessun problema critico rilevato nell'audit tecnico."))
    else:
        pdf.set_font("Helvetica", size=11)
        for it in issues_list:
            msg = str(it.get("message") or "").strip() or "Problema tecnico"
            code = str(it.get("code") or "").strip()
            line = it.get("line")
            suffix = ""
            if code:
                suffix += f" [{code}]"
            if isinstance(line, int) and line > 0:
                suffix += f" (linea {line})"
            pdf.multi_cell(0, 6, clean_text(f"- {msg}{suffix}"))
            pdf.ln(1)

    pdf.set_y(-18)
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(120)
    pdf.cell(0, 8, clean_text("Generated by Client Sniper Intelligence"), align="C")

    out = pdf.output(dest="S")
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    return out.encode("latin1")
